local function map(mode, lhs, rhs, desc, opts)
  opts = opts or {}
  opts.desc = desc
  vim.keymap.set(mode, lhs, rhs, opts)
end

local function cmd(command)
  return "<cmd>" .. command .. "<cr>"
end

local function nmap(lhs, rhs, desc, opts)
  map("n", lhs, rhs, desc, opts)
end

local function xmap(lhs, rhs, desc, opts)
  map("x", lhs, rhs, desc, opts)
end

local function ncmd(lhs, command, desc, opts)
  nmap(lhs, cmd(command), desc, opts)
end

local function xcmd(lhs, command, desc, opts)
  xmap(lhs, cmd(command), desc, opts)
end

ncmd("<C-s>", "write", "Save")
ncmd("<Esc>", "nohlsearch", "Clear search highlight")
ncmd("[p", [[exe "iput! " . v:register]], "Paste above")
ncmd("]p", [[exe "iput "  . v:register]], "Paste below")

nmap("<leader>aa", function()
  require("sidekick.cli").toggle({ name = "codex", focus = true })
end, "Sidekick Codex")
ncmd("<leader>aC", "CodeCompanionActions", "AI actions")
ncmd("<leader>ac", "CodeCompanionChat Toggle", "Toggle AI chat")
ncmd("<leader>ah", "CodeCompanionHistory", "AI chat history")
ncmd("<leader>ai", "CodeCompanion", "Inline AI prompt")
nmap("<leader>ad", function()
  require("sidekick.cli").close()
end, "Close Sidekick CLI")
nmap("<leader>af", function()
  require("sidekick.cli").send({ msg = "{file}" })
end, "Send file to Sidekick")
nmap("<leader>aj", function()
  require("sidekick").nes_jump_or_apply()
end, "NES jump/apply")
nmap("<leader>aN", function()
  require("sidekick.nes").update()
end, "Refresh NES")
nmap("<leader>an", function()
  require("sidekick.nes").toggle()
end, "Toggle NES")
nmap("<leader>ap", function()
  require("sidekick.cli").prompt()
end, "Prompt Sidekick CLI")
nmap("<leader>as", function()
  require("sidekick.cli").select({ filter = { installed = true } })
end, "Select Sidekick CLI")
nmap("<leader>at", function()
  require("sidekick.cli").send({ msg = "{this}" })
end, "Send current context")
nmap("<leader>ax", function()
  require("sidekick.nes").clear()
end, "Clear NES suggestion")

ncmd("<leader>qw", "q", "Quit window")
ncmd("<leader>qq", "qa", "Quit all")
ncmd("<leader>qr", "restart", "Restart Neovim")
ncmd("<leader>qx", "x", "Write and quit")

ncmd("<leader>ba", "b#", "Alternate buffer")
nmap("<leader>bd", function()
  MiniBufremove.delete()
end, "Delete buffer")
nmap("<leader>bD", function()
  MiniBufremove.delete(0, true)
end, "Delete buffer forcefully")
nmap("<leader>bo", function()
  local current = vim.api.nvim_get_current_buf()
  for _, info in ipairs(vim.fn.getbufinfo({ buflisted = 1 })) do
    if info.bufnr ~= current then
      MiniBufremove.delete(info.bufnr)
    end
  end
end, "Delete other buffers")
nmap("<leader>bO", function()
  local current = vim.api.nvim_get_current_buf()
  for _, info in ipairs(vim.fn.getbufinfo({ buflisted = 1 })) do
    if info.bufnr ~= current then
      MiniBufremove.delete(info.bufnr, true)
    end
  end
end, "Delete other buffers forcefully")
nmap("<leader>bs", function()
  vim.api.nvim_win_set_buf(0, vim.api.nvim_create_buf(true, true))
end, "Scratch buffer")
nmap("<leader>bw", function()
  MiniBufremove.wipeout()
end, "Wipe out buffer")
nmap("<leader>bW", function()
  MiniBufremove.wipeout(0, true)
end, "Wipe out buffer forcefully")

nmap("<leader>e", function()
  MiniFiles.open()
end, "Open file explorer")
nmap("<leader>ed", function()
  MiniFiles.open()
end, "Explore current working directory")
nmap("<leader>ef", function()
  MiniFiles.open(vim.api.nvim_buf_get_name(0))
end, "Explore current file directory")
nmap("<leader>en", function()
  MiniNotify.show_history()
end, "Show notifications")
nmap("<leader>eq", function()
  local winid = vim.fn.getqflist({ winid = true }).winid
  vim.cmd(winid ~= 0 and "cclose" or "copen")
end, "Toggle quickfix list")
nmap("<leader>eQ", function()
  local winid = vim.fn.getloclist(0, { winid = true }).winid
  vim.cmd(winid ~= 0 and "lclose" or "lopen")
end, "Toggle location list")

ncmd("<leader>f/", [[Pick history scope="/"]], "Search history")
ncmd("<leader>f:", [[Pick history scope=":"]], "Command history")
ncmd("<leader>fa", [[Pick git_hunks scope="staged"]], "Added hunks")
ncmd("<leader>fA", [[Pick git_hunks path="%" scope="staged"]], "Added hunks in buffer")
ncmd("<leader>fb", "Pick buffers", "Find buffers")
ncmd("<leader>fc", "Pick git_commits", "Find commits")
ncmd("<leader>fC", [[Pick git_commits path="%"]], "Find buffer commits")
ncmd("<leader>fd", [[Pick diagnostic scope="all"]], "Workspace diagnostics")
ncmd("<leader>fD", [[Pick diagnostic scope="current"]], "Buffer diagnostics")
ncmd("<leader>ff", "Pick files", "Find files")
ncmd("<leader>fg", "Pick grep_live", "Live grep")
ncmd("<leader>fG", [[Pick grep pattern="<cword>"]], "Grep current word")
ncmd("<leader>fh", "Pick help", "Find help tags")
ncmd("<leader>fH", "Pick hl_groups", "Find highlight groups")
ncmd("<leader>fl", [[Pick buf_lines scope="all"]], "Find lines")
ncmd("<leader>fL", [[Pick buf_lines scope="current"]], "Find buffer lines")
ncmd("<leader>fm", "Pick git_hunks", "Modified hunks")
ncmd("<leader>fM", [[Pick git_hunks path="%"]], "Modified hunks in buffer")
ncmd("<leader>fr", "Pick resume", "Resume picker")
ncmd("<leader>fR", [[Pick lsp scope="references"]], "LSP references")
ncmd("<leader>fs", [[Pick lsp scope="workspace_symbol_live"]], "Workspace symbols")
ncmd("<leader>fS", [[Pick lsp scope="document_symbol"]], "Document symbols")
ncmd("<leader>fv", [[Pick visit_paths cwd=""]], "Visited paths")
ncmd("<leader>fV", "Pick visit_paths", "Visited paths in cwd")
nmap("<leader>fq", function()
  require("grug-far").open()
end, "Find and replace")
nmap("<leader>fQ", function()
  require("grug-far").open({ prefills = { paths = vim.fn.expand("%") } })
end, "Find and replace in buffer")

ncmd("<leader>gg", "TermToggleLazygit", "Lazygit toggle")
ncmd("<leader>ga", "Git diff --cached", "Git diff staged")
ncmd("<leader>gA", "Git diff --cached -- %", "Git diff staged buffer")
ncmd("<leader>gc", "Git commit", "Git commit")
ncmd("<leader>gC", "Git commit --amend", "Git amend")
ncmd("<leader>gd", "Git diff", "Git diff")
ncmd("<leader>gD", "Git diff -- %", "Git diff buffer")
ncmd("<leader>gl", [[Git log --pretty=format:\%h\ \%as\ │\ \%s --topo-order]], "Git log")
ncmd("<leader>gL", [[Git log --pretty=format:\%h\ \%as\ │\ \%s --topo-order --follow -- %]], "Git log buffer")
nmap("<leader>go", function()
  MiniDiff.toggle_overlay()
end, "Toggle diff overlay")
nmap("<leader>gs", function()
  MiniGit.show_at_cursor()
end, "Show git info")

nmap("<leader>kk", function()
  require("kubectl").toggle({ tab = false })
end, "kubectl toggle")
nmap("<leader>kK", function()
  require("kubectl").toggle({ tab = true })
end, "kubectl toggle in tab")

nmap("<leader>db", function()
  require("dap").toggle_breakpoint()
end, "Toggle breakpoint")
nmap("<leader>dB", function()
  require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, "Set conditional breakpoint")
nmap("<leader>dc", function()
  require("dap").continue()
end, "Continue debugging")
nmap("<leader>de", function()
  require("dap.ui.widgets").hover()
end, "Evaluate expression")
nmap("<leader>dg", function()
  require("dap-go").debug_test()
end, "Debug nearest Go test")
nmap("<leader>dG", function()
  require("dap-go").debug_last_test()
end, "Debug last Go test")
nmap("<leader>di", function()
  require("dap").step_into()
end, "Step into")
nmap("<leader>dm", function()
  require("dap-python").test_method()
end, "Debug Python test method")
nmap("<leader>dM", function()
  require("dap-python").test_class()
end, "Debug Python test class")
nmap("<leader>do", function()
  require("dap").step_over()
end, "Step over")
nmap("<leader>dO", function()
  require("dap").step_out()
end, "Step out")
nmap("<leader>dp", function()
  require("dap").pause()
end, "Pause debugging")
nmap("<leader>dq", function()
  require("dap").repl.toggle()
end, "Toggle DAP REPL")
nmap("<leader>dr", function()
  require("dap").run_last()
end, "Run last debug config")
nmap("<leader>dt", function()
  require("dap").terminate()
end, "Terminate debugging")
ncmd("<leader>du", "DapViewToggle", "Toggle debug UI")
ncmd("<leader>dv", "DapVirtualTextToggle", "Toggle debug virtual text")
ncmd("<leader>dw", "DapViewWatch", "Watch expression")
nmap("<leader>dx", function()
  require("dap").clear_breakpoints()
end, "Clear breakpoints")
nmap("<leader>dL", function()
  require("dap").set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end, "Set log point")

nmap("<leader>la", function()
  vim.lsp.buf.code_action()
end, "Actions")
nmap("<leader>lf", function()
  require("conform").format({ async = true, lsp_format = "fallback" })
end, "Format buffer")
nmap("<leader>lG", function()
  local lint = require("lint")
  if lint.linters.gitleaks == nil then
    vim.notify("gitleaks linter is not available in nvim-lint", vim.log.levels.WARN)
    return
  end
  lint.try_lint("gitleaks")
end, "Run Gitleaks")
nmap("<leader>lh", function()
  vim.lsp.buf.hover()
end, "Hover")
nmap("<leader>li", function()
  vim.lsp.buf.implementation()
end, "Implementation")
nmap("<leader>ll", function()
  require("lint").try_lint()
end, "Lint buffer")
nmap("<leader>lL", function()
  vim.lsp.codelens.run()
end, "Run code lens")
ncmd("<leader>lM", "RenderMarkdown toggle", "Markdown render toggle")
ncmd("<leader>lP", "MarkdownPreviewToggle", "Markdown preview toggle")
nmap("<leader>lr", function()
  vim.lsp.buf.rename()
end, "Rename")
nmap("<leader>lR", function()
  vim.lsp.buf.references()
end, "References")
nmap("<leader>ls", function()
  vim.lsp.buf.definition()
end, "Source definition")
nmap("<leader>lt", function()
  vim.lsp.buf.type_definition()
end, "Type definition")

nmap("<leader>mf", function()
  MiniMap.toggle_focus()
end, "Toggle map focus")
nmap("<leader>mr", function()
  MiniMap.refresh()
end, "Refresh map")
nmap("<leader>ms", function()
  MiniMap.toggle_side()
end, "Toggle map side")
nmap("<leader>mt", function()
  MiniMap.toggle()
end, "Toggle map")

nmap("<leader>na", function()
  require("neotest").run.attach()
end, "Attach to running test")
nmap("<leader>nd", function()
  require("neotest").run.run({ strategy = "dap" })
end, "Debug nearest test")
nmap("<leader>nf", function()
  require("neotest").run.run(vim.fn.expand("%"))
end, "Run test file")
nmap("<leader>nl", function()
  require("neotest").run.run_last()
end, "Run last test")
nmap("<leader>nn", function()
  require("neotest").run.run()
end, "Run nearest test")
nmap("<leader>no", function()
  require("neotest").output.open({ enter = true, auto_close = true })
end, "Open test output")
nmap("<leader>nO", function()
  require("neotest").output_panel.toggle()
end, "Toggle test output panel")
nmap("<leader>nq", function()
  require("neotest").run.stop()
end, "Stop test run")
nmap("<leader>ns", function()
  require("neotest").summary.toggle()
end, "Toggle test summary")
nmap("<leader>nS", function()
  require("neotest").run.run(vim.fn.getcwd())
end, "Run test suite")
nmap("<leader>nw", function()
  require("neotest").watch.toggle(vim.fn.expand("%"))
end, "Watch test file")

ncmd("<leader>oa", "OverseerTaskAction", "Overseer task action")
ncmd("<leader>ob", "DBUIFindBuffer", "Find DBUI buffer")
ncmd("<leader>od", "DBUIToggle", "Database UI toggle")
ncmd("<leader>oD", "DBUIAddConnection", "Add database connection")
ncmd("<leader>oo", "OverseerToggle! right", "Toggle Overseer task list")
ncmd("<leader>or", "OverseerRun", "Run Overseer task")
ncmd("<leader>oR", "OverseerRestartLast", "Restart last Overseer task")
ncmd("<leader>os", "OverseerShell", "Run shell task")
nmap("<leader>ot", function()
  MiniTrailspace.trim()
end, "Trim trailing whitespace")
nmap("<leader>ow", function()
  MiniMisc.resize_window()
end, "Resize to default width")
nmap("<leader>oz", function()
  MiniMisc.zoom()
end, "Toggle zoom")

nmap("<leader>ra", function()
  require("kulala").run_all()
end, "Run all requests")
nmap("<leader>rb", function()
  require("kulala").open()
end, "Request scratchpad")
nmap("<leader>rc", function()
  require("kulala").copy()
end, "Copy as curl")
nmap("<leader>ri", function()
  require("kulala").inspect()
end, "Inspect request")
nmap("<leader>rr", function()
  require("kulala").run()
end, "Run request")
nmap("<leader>rR", function()
  require("kulala").replay()
end, "Replay request")
nmap("<leader>rs", function()
  require("kulala").show_stats()
end, "Show request stats")
nmap("<leader>ry", function()
  require("kulala").from_curl()
end, "Import from curl")

nmap("<leader>sd", function()
  MiniSessions.select("delete")
end, "Delete session")
nmap("<leader>sn", function()
  vim.ui.input({ prompt = "Session name: " }, MiniSessions.write)
end, "Write named session")
nmap("<leader>sr", function()
  MiniSessions.read()
end, "Read default session")
nmap("<leader>sR", function()
  MiniSessions.restart()
end, "Restart into session")
nmap("<leader>sw", function()
  MiniSessions.write(MiniSessions.config.file)
end, "Write local session")

ncmd("<leader>tt", "TermToggleVertical", "Toggle vertical terminal")
ncmd("<leader>tT", "TermToggleHorizontal", "Toggle horizontal terminal")
ncmd("<leader>tf", "TermToggleFloat", "Toggle floating terminal")
ncmd("<leader>tg", "TermToggleLazygit", "Toggle Lazygit")
ncmd("<leader>tl", "TermToggleLast", "Toggle last terminal")

nmap("<leader>vc", function()
  local sort_latest = MiniVisits.gen_sort.default({ recency_weight = 1 })
  MiniExtra.pickers.visit_paths(
    { cwd = "", filter = "core", sort = sort_latest },
    { source = { name = "Core visits (all)" } }
  )
end, "Core visits")
nmap("<leader>vC", function()
  local sort_latest = MiniVisits.gen_sort.default({ recency_weight = 1 })
  MiniExtra.pickers.visit_paths(
    { filter = "core", sort = sort_latest },
    { source = { name = "Core visits (cwd)" } }
  )
end, "Core visits in cwd")
nmap("<leader>vl", function()
  MiniVisits.add_label()
end, "Add visit label")
nmap("<leader>vL", function()
  MiniVisits.remove_label()
end, "Remove visit label")
nmap("<leader>vv", function()
  MiniVisits.add_label("core")
end, "Add core visit label")
nmap("<leader>vV", function()
  MiniVisits.remove_label("core")
end, "Remove core visit label")

nmap("(", "gxiagxila", "Swap argument left", { remap = true })
nmap(")", "gxiagxina", "Swap argument right", { remap = true })

xmap("<leader>lf", function()
  require("conform").format({ async = true, lsp_format = "fallback" })
end, "Format selection")
xcmd("<leader>aC", "CodeCompanionActions", "AI actions")
xcmd("<leader>ac", "CodeCompanionChat Add", "Add selection to AI chat")
xmap("<leader>av", function()
  require("sidekick.cli").send({ msg = "{selection}" })
end, "Send selection to Sidekick")
xmap("<leader>fq", function()
  require("grug-far").open()
end, "Find and replace selection")
xmap("<leader>ds", function()
  require("dap-python").debug_selection()
end, "Debug selection")
xmap("<leader>gs", function()
  MiniGit.show_at_cursor()
end, "Show git info")
